### ISSUE TITLE
file_create does not recognize identical files under Ruby 1.9.2

### ISSUE THREAD

**Issue by tf** [rails/thor#166]
Hi,

we noticed that bundler keeps overwriting generated files on reruns even if the diffs are empty. I suspect this is caused  by encoding issues: File.binread returns ASCII, while ruby's internal string representation of the rendered content probably uses  UTF8. Under Ruby 1.8.7 everything works fine. Also replacing File.binread with File.read makes it work on my machine (TM). There might though be other cases, which depend on binread instead of read.

I'd be glad to supply a patch once we have settled for a solution. 

Best,
Tim

**Comment by rafaelfranca** [comment]
This should be fixed now
