### ISSUE TITLE
FIPS compatibility

### ISSUE THREAD

**Issue by voxik** [rails/thor#287]
I am testing Thor in FIPS mode [1]. Unfortunately it fails with following error:

```
md5_dgst.c(78): OpenSSL internal error, assertion failed: Digest MD5 forbidden in FIPS mode!
```

Would you please consider to use different hashing algorithm such as SHA256 to make Thor FIPS compatible?

[1] http://en.wikipedia.org/wiki/FIPS_140

**Comment by trevor-vaughan** [comment]
:+1: This is still an issue and breaking on FIPS enabled systems. It would be great to use an updated cipher or be able to select a default.

However, it should not do 'require/md5' by default since that alone will break on a system with FIPS enabled.

**Comment by op-ct** [comment]
+1

FIPS mode breaks thor and any application that uses it (e.g., bundler).

What need to be done to get this patch merged?

**Comment by david-a-wheeler** [comment]
MD5 was broken a long, long time ago.  It's long past time to switch to a stronger algorithm like SHA256 or SHA-3.  It's not just FIPS mode - MD5 isn't in FIPS because it's a bad idea.  Please switch!

**Comment by stanhu** [comment]
I submitted https://github.com/rails/thor/pull/785. Maybe a pull request will get more attention.

I'm not sure how severe the backwards compatibility problem actually is.
