### ISSUE TITLE
Documentation links broken

### ISSUE THREAD

**Issue by chrisarcand** [rails/thor#518]
The documentation links in the wiki reference rubydoc.info via the @wycats repo instead of this one; Even though GitHub redirects wycats/thor to here, the lines referenced in the documentation are completely wrong :confused: 

More importantly, it looks like clicking "View on GitHub" within the documentation on rubydoc.info gives a 404 on everything. That's due to the difference between (examples):

https://github.com/erikhuda/thor/blob/Thor/lib/thor/shell/basic.rb#L242

and

https://github.com/erikhuda/thor/blob/master/lib/thor/shell/basic.rb#L242

Help? I'm not intimately familiar with how YARD is generated along with rubydoc.info so wasn't sure where to look.

**Comment by colby-swandale** [comment]
@chrisarcand i've regen the documentation on rubydoc.info, can you check if the links are working now?

**Comment by chrisarcand** [comment]
Hmm it's something else... The URLs generated are a little off.

Here's an example of the link I'm talking about:

![image](https://cloud.githubusercontent.com/assets/2430490/26785550/045cf7f8-49d1-11e7-8f0e-cdbc3d41df62.png)

Looks like it's still got the incorrect 'branch' parameter (uses `/Thor` instead of `/master`)

**Comment by colby-swandale** [comment]
I need to chat to the ruby-doc.info team, the page is still continuing to use the broken URLs when It shouldn't be.

**Comment by p8** [comment]
@chrisarcand I know this is an old issue, but can it be closed? 😄 
It also seems to be an rubydoc.info issue which has been fixed/closed.
