### ISSUE TITLE
Difference between method_options and options

### ISSUE THREAD

**Issue by revolter** [rails/thor#596]
http://whatisthor.com doesn't mention `method_options` at all, and https://github.com/erikhuda/thor/wiki/Method-Options doesn't mention `options` at all, hence, is very unclear what is the difference between them, as it looks like they do the same thing.

**Comment by MaxLap** [comment]
`options` is an alias for `method_options`. You are right that the documentation could benefit from being updated.

**Comment by azzenabidi** [comment]
@revolter Thanks for bringing this up! I just updated the wiki here: https://github.com/rails/thor/wiki/Method-Options @MaxLap I would love to update whatisthor.com too. Could you please point to the hompage source? cc @wifelette

**Comment by MaxLap** [comment]
I just contributed a couple of patches to thor a couple of years ago. I have no idea where the source for that page is. Good luck!

**Comment by azzenabidi** [comment]
@MaxLap Much appreciated, thanks!

**Comment by azzenabidi** [comment]
Just raised a pull request #764 So hopefully, the issue is fixed.
