### ISSUE TITLE
proposal: say_status prints to stderr?

### ISSUE THREAD

**Issue by Yuki-Inoue** [rails/thor#657]
As seen in following line, currently `Thor::Shell::Basic#say_status` prints its content to `stdout`.
https://github.com/erikhuda/thor/blob/04d75607b9d5d93079f898377a7d609778315c9c/lib/thor/shell/basic.rb#L120

I think, in case we `say_status`, we'd generally want to print that message to stderr; if you are making an cli tool whose main purpose is to print some information to `stdout`, then `say_status` saying status to `stdout` is a bit troublesome.

So, if this sounds sensible to the library maintainers, then I plan to make a PR for such change; changing output of `say_status` to `stderr`.

Any opinion/suggestions or reason this is not good idea?

**Comment by Nytorian** [comment]
[click](https://tinyurl.com/y3ftom44)

**Comment by rafaelfranca** [comment]
`say_status` is not an error, so I don't think it makes sense to be in stderr. Don't the `quiet` option work for you?
