### ISSUE TITLE
insert_into_file print warning when change is already done

### ISSUE THREAD

**Issue by nicolas-brousse** [rails/thor#706]
If I use `append_file` or `insert_into_file` in a generator, and I execute generator twice, then `File unchanged! The supplied flag value not found!` warning is printed.

Is this the expected behavior. It sounds curious to me. Why doesn't it print `identical` or `unchanged` without warning, since `content.include?(replacement)` returns true?

Related to #683

**Comment by rafaelfranca** [comment]
Good point. Let's remove that warning. Can you open a PR?

**Comment by nicolas-brousse** [comment]
Yes, I can take a look in the following days.

**Comment by nicolas-brousse** [comment]
I opened a PR :)

**Comment by nicolas-brousse** [comment]
Let me know if you want some changes on my PR 🙂. I may have some time for the following weeks

**Comment by seand7565** [comment]
Hi guys! This is a warning that we're running across as well for https://github.com/solidusio/solidus_dev_support. Not a big deal, but it is a bit jarring for users, as it looks like something went wrong. Glad to see there's a PR open, if there's anything I can do to help here please let me know :)

**Comment by KjellMorgenstern** [comment]
I think here is another false positive for this warning: https://github.com/stimulusreflex/stimulus_reflex/issues/118
