### ISSUE TITLE
inject_into_file with pretend reports file unchanged

### ISSUE THREAD

**Issue by scambra** [rails/thor#707]
Before this commit 25dc317f71f5d212d63fbd9eb4b81bd437ee762f inject_into_file with pretend option was printing inject line, but now it complains about file didn't change.

The best way it would try to replace and return success, without writing file

**Comment by dorner** [comment]
@scambra not sure if you're still interested in this - it looks good to me but there should be a spec to cover this behavior.

**Comment by scambra** [comment]
yes, I'm still interested, I will look into specs whenever I can

**Comment by scambra** [comment]
@dorner I have added a spec for inject_into_file with pretend
