### ISSUE TITLE
Documentation of Thor::Actions#initialize incomplete

### ISSUE THREAD

**Issue by paddor** [rails/thor#727]
https://rubydoc.info/github/wycats/thor/master/Thor%2FActions:initialize says:

> The actions default behavior. Can be :invoke or :revoke. It also accepts :force, :skip and :pretend to set the behavior and the respective option.

But there's not a word about what these options do. I can guess what `:force` and `:pretend` do with `#copy_file`, but not so with `:skip`.

**Comment by rafaelfranca** [comment]
The explanation is here https://github.com/erikhuda/thor/blob/34df888d721ecaa8cf0cea97d51dc6c388002742/lib/thor/actions.rb#L48-L60. Can you open a PR expanding the documentation?

**Comment by azzenabidi** [comment]
Hi @rafaelfranca, happy to work on this. Could you please point me to the relevant repo? Thanks! cc @paddor
