### ISSUE TITLE
thor-1.1.0 on Ubuntu 20.04.3 Cannot Run Any Rails DB Commands

### ISSUE THREAD

**Issue by MikeBarberry** [rails/thor#760]
Been running into an issue running rails db:create, or any other db command. 

I get a TypeError: superclass mismatch for class Thor. Coming from gems/gems/thor-1.1.0/lib/thor/command.rb. 

I reinstalled ruby-thor on Ubuntu 20.04.3 and still having the same issue. 

The only thing that works is:
dpkg -r --force-depends  ruby-thor
gem install thor

But the problem then is that my OS tells me there is a problem with my packages and I cannot update anything. To be able to apply any system updates, I'm required to reinstall the broken package.

**Comment by dorner** [comment]
Looks like this might happen if you're loading the gem twice for some reason. That file uses `class Command < Struct.new` which will cause this error if it's loaded twice.

**Comment by rafaelfranca** [comment]
Thank you for the report but this is more an ubuntu issue than an issue in the thor code. Please report to their issue tracker.

**Comment by MikeBarberry** [comment]
I installed rbenv and moved my gem $HOME if anyone runs into this at some point in the future
