### ISSUE TITLE
Getting "DidYouMean::SPELL_CHECKERS.merge!" warning with Ruby 3.1

### ISSUE THREAD

**Issue by jasnow** [rails/thor#763]
It appears that some repos using thor gem with Ruby 3.1 have this warning message when running "rake" command:
```
DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. 
Please call DidYouMean.correct_error(error_name, spell_checker) instead.
```
Find SHELL_CHECKERS string is this file (line 105): thor-1.1.0/lib/thor/error.rb

Sample (Rails 6.1/Ruby 3.1) App: https://github.com/jasnow/rt_demo_app

**Comment by andrehjr** [comment]
Should be fixed by https://github.com/rails/thor/pull/761

**Comment by jasnow** [comment]
Duplicate so closing
