### ISSUE TITLE
CI not running clean 

### ISSUE THREAD

**Issue by timdiggins** [rails/thor#781]
🌈  CI seems to be not running clean because of: 

* spec/parser/options_spec.rb:119  #777 
* ruby 3.0+ failures with specs expecting intracoversion between final hash argument and keyword args #779
* coveralls SSL error (seems to be same as https://github.com/lemurheavy/coveralls-ruby/issues/163 - maybe replace with [coveralls-reborn](https://github.com/tagliala/coveralls-ruby-reborn)?) #778 

There's a combination PR #780 if you prefer a simple one-shot to get to green.

**Comment by dorner** [comment]
I think the combo PR looks fine! @rafaelfranca
