### ISSUE TITLE
Replacement for thor?

### ISSUE THREAD

**Issue by ericgross** [rails/thor#794]
Has anyone considered migrating away from using thor?

If so, what did you consider/choose?

It seems that rake and POROs are the most obvious alternatives, both with their disadvantages. I like the idea of thor but it doesn't seem to be maintained.

**Comment by dorner** [comment]
There's still some activity, although it does seem to be less active than other parts of Rails. Unfortunately it seems like @rafaelfranca is the only admin for this and he has his hands full with all the other parts of the Rails ecosystem. :(

**Comment by ericgross** [comment]
Makes sense. I'm not looking for any new features - only compatibility with Rails 7 - does anyone know if that's planned?

**Comment by dorner** [comment]
What is the issue with Rails 7? Is there an existing bug?

**Comment by ericgross** [comment]
Yeah, it's not working for us, see #793

**Comment by dorner** [comment]
I added a comment there, please take a look.

**Comment by rafaelfranca** [comment]
Thor is completely compatible with Rails 7. Even Rails 7 itself uses thor.
