### ISSUE TITLE
How to copy directory of *.tt files?

### ISSUE THREAD

**Issue by alec-c4** [rails/thor#803]
Hi!
Is it possible to copy a directory of *.tt files without executing template engine. I'd like to improve my [rails templates](https://github.com/alec-c4/kickstart) and add custom scaffold templates (views, controllers and specs), but every time I use `directory` method

```ruby
directory "lib/templates", force: true
```

I see an exception when thor tries to start template engine for those files. How to **just copy** my directory?

**Comment by rafaelfranca** [comment]
You can use `FileUtils.cp`. But I'm ok to add a new method that copies directory without using templates. Closing the issue since this is a feature request, but if you want to open a PR to add a new action, please do it.
