### ISSUE TITLE
method_option does not correctly parsed

### ISSUE THREAD

**Issue by daddygongon** [rails/thor#808]
The method_option as shown below works expectedly:
``` ruby
    method_option :force, :type => :boolean, :default => false,
                         :aliases => "-f", :desc => "forcely replace"
```
When using format below, it does not work
``` ruby
    method_option :force => false, :aliases => "-f", :desc => "forcely replace"
```

If the code is wrong, the sample on the document below should be written in more detail.
- https://github.com/rails/thor/wiki/Method-Options

Thanks!

**Comment by p8** [comment]
I think the problem here is that there are two separate methods:

```ruby
    method_option  :force => false, :aliases => "-f", :desc => "forcely replace" # does not work
    method_options :force => false, :aliases => "-f", :desc => "forcely replace" # does work
```

**Comment by daddygongon** [comment]
Sorry, the long time makes me lost the point.

**Comment by mensfeld** [comment]
It's interesting because it did work for me. I had aliases working and had to apply following patch in Karafka after 1.3.0 was released yesterday: https://github.com/karafka/karafka/pull/1678
