### ISSUE TITLE
Are there any plans to drop support for older versions of Ruby?

### ISSUE THREAD

**Issue by shuuuuun** [rails/thor#813]
This gem currently supports Ruby 2.0 and above.
https://github.com/rails/thor/blob/376e141adb594f3146c57e98151b97a20c93c484/thor.gemspec#L25
https://github.com/rails/thor/blob/376e141adb594f3146c57e98151b97a20c93c484/.github/workflows/tests.yml#L9

At this time, the officially supported Ruby version is 2.7 or later.
(2.7 will soon be EOL as well.)
https://www.ruby-lang.org/en/downloads/branches/

I am working on a PR for another issue, but it is not compatible with older Ruby.
https://github.com/rails/thor/pull/812#issuecomment-1448346323

Thank you.

**Comment by rafaelfranca** [comment]
[Now that bundler dropped support to old Rubies we can as well](https://github.com/rubygems/rubygems/commit/77e7b79d657c20ecb0dccc73d38d180accf90aac). I'll do it

**Comment by shuuuuun** [comment]
Oh, it depended on the support status of bundler.
Thank you very much!
