### ISSUE TITLE
Default value not printed in help if option type boolean and default value is false

### ISSUE THREAD

**Issue by hadmut** [rails/thor#819]
Hi, 

usually the help output generated by a thor app lists the options for the class and the actions, and shows the default value if a default value is set. 

But for 
  method_option :save,  type: :boolean, desc: "save file" , default: false

the default value is printed only of it is true, not false.  (Thor 1.2.1)

regards

**Comment by p8** [comment]
@hadmut this can now be closed, right?

**Comment by hadmut** [comment]
I didn't find the time to verify it yet, but I do fully trust you.
