### ISSUE TITLE
New release to fix "File unchanged!" warning?

### ISSUE THREAD

**Issue by mattbrictson** [rails/thor#853]
When running `rails app:update` or when re-running popular installers like `turbo:install`, users can see scary red warnings like these, even though there is no underlying problem:

> File unchanged! Either the supplied flag value not found or the content has already been inserted!

![Screenshot 2023-07-19 at 4 46 32 PM](https://github.com/rails/thor/assets/189693/918ab35c-ca87-4e73-9433-767f14d39107)

(☝️ `rails app:update` output)

The underlying issue was raised in #706 and fixed earlier this year in #709. However the fix has not yet been published to rubygems.

Could the maintainers consider pushing a new release soon to address this issue? Thanks!

**Comment by rafaelfranca** [comment]
Released
